dist: xenial
install:
  # output errors to stdout because qemu syscalls annoying
- travis_wait 80 sudo ./build.sh 2>&1
branches:
  only:
    - travis_dev
    # tag regex
    - /^v\d+\.\d+\.\d+.*$/
language: minimal
before_install:
  - sudo dpkg --add-architecture armhf
  - sudo apt install libpython3.7-dev:armhf libtiff-dev:armhf zlib1g-dev:armhf libjpeg-dev:armhf libpng-dev:armhf libavcodec-dev:armhf libavformat-dev:armhf libswscale-dev:armhf libv4l-dev:armhf libxvidcore-dev:armhf libx264-dev:armhf
  - curl -O http://ftp.us.debian.org/debian/pool/main/c/checkinstall/checkinstall_1.6.2-4_amd64.deb
  - dpkg -i checkinstall_1.6.2-4_amd64.deb
cache:
  directories:
    - cache
addons:
  apt:
    packages:
      - git
      - vim
      - parted
      - quilt
      - coreutils
      - debootstrap
      - qemu-user-static
      - zerofree
      - zip
      - dosfstools
      - bsdtar
      - libcap2-bin
      - rsync
      - grep
      - udev
      - xz-utils
      - curl
      - xxd
      - file
      - kmod
      - crossbuild-essential-armhf
      - gfortran-arm-linux-gnueabihf
      - cmake
      - pkg-config
      - python3-dev
      - python3.7-dev
      - python3-numpy
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "deploy/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: homebrew-limelight/hbll-gen
    tags: true
