dist: bionic 
install:
  # output errors to stdout because qemu syscalls annoying
- travis_wait 80 sudo ./build-docker.sh 2>&1
branches:
  only:
    - travis-dev
    # tag regex
    - /^v\d+\.\d+\.\d+.*$/
language: minimal
cache:
  directories:
    - cache
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "deploy/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: opensight-cv/opsi-gen
    tags: true
