dist: xenial
install:
  # output errors to stdout because qemu syscalls annoying
- travis_wait 40 sudo ./build.sh 2>&1
branches:
  only:
    # tag regex
    - /^v\d+\.\d+\.\d+.*$/
language: minimal
addons:
  apt:
    packages:
    - coreutils
    - quilt
    - parted
    - qemu-user-static
    - debootstrap
    - zerofree
    - zip
    - dosfstools
    - bsdtar
    - libcap2-bin
    - grep
    - rsync
    - xz-utils
    - file
    - git
    - curl
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "deploy/*.zip"
  file_glob: true
  skip_cleanup: true
  on:
    repo: homebrew-limelight/hbll-gen
    tags: true
