dist: bionic 
install:
  # output errors to stdout because qemu syscalls annoying
- sudo ./build-docker.sh
branches:
  only:
    - travis-dev
    # tag regex
    - /^v\d+\.\d+\.\d+.*$/
language: minimal
cache:
  directories:
    - cache
deploy:
  provider: releases
  api_key: $GITHUB_KEY
  file: "deploy/*.zip"
  file_glob: true
  skip_cleanup: true
  body: "You can view the full changelog for this release at https://github.com/opensight-cv/opensight/releases/$TRAVIS_TAG"
  on:
    repo: opensight-cv/opsi-gen
    tags: true
